apiVersion: v1
kind: Service
metadata:
  annotations:
    created-by: Automated By Pipeline
    team: AI Team
    exposure-type: internal
  name: ai-polishing
  namespace: foundation
  labels:
    app.kubernetes.io/instance: vllm-model
    app.kubernetes.io/name: vllm-model
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 80
      name: http
  selector:
    app.kubernetes.io/instance: ai-polishing
    app.kubernetes.io/name: ai-polishing
